name: sample practice workflow
on: push
jobs:
    welcome-user:
        runs-on: ubuntu-22.04
        steps:
            - name: Echo user name
              run: echo "Hi Jerin"
            - name: checkout repo
              uses: actions/checkout@v6
            - name: List files
              run: ls -lart
            - name: View Readme file
              run: cat README.md